// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using The_Right_Fit.Data;

#nullable disable

namespace The_Right_Fit.Migrations
{
    [DbContext(typeof(The_Right_FitContext))]
    [Migration("20260117164645_identitystuff")]
    partial class identitystuff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        },
                        new
                        {
                            UserId = "99999999-8888-7777-6666-555555555555",
                            RoleId = "bd2bcf0c-20db-474f-8407-5a6b159518bb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("The_Right_Fit.Data.The_Right_FitUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "abdf0ebb-1247-4bf3-bf88-3b8fb7b49b07",
                            Email = "admin@therightfit.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@THERIGHTFIT.COM",
                            NormalizedUserName = "ADMIN@THERIGHTFIT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJFuZahxxcJh941Migc3naghnuQ6CEr9lf1TAxcupEHG6NWIprc6IBBqJCY9jPC1nA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb55c67f-ee63-4e33-b146-de13d9540f66",
                            TwoFactorEnabled = false,
                            UserName = "admin@therightfit.com"
                        },
                        new
                        {
                            Id = "99999999-8888-7777-6666-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e3317ec4-c6b6-4bec-ac2e-60a7e017a3d2",
                            Email = "user@therightfit.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@THERIGHTFIT.COM",
                            NormalizedUserName = "USER@THERIGHTFIT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBw+pDE0JpdI/CKNzSg3yx1GMw/cuW/MhLpcPaA9JNguG3NsiNiADuGYgV4rwNAZBg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6b1be1b-642a-4450-a15f-00703d8928ee",
                            TwoFactorEnabled = false,
                            UserName = "user@therightfit.com"
                        });
                });

            modelBuilder.Entity("The_Right_Fit.Domain.DietLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomFoodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerIdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QuantityServings")
                        .HasColumnType("float");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DietLog");
                });

            modelBuilder.Entity("The_Right_Fit.Domain.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5398),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5414),
                            EquipmentNeeded = "Barbell",
                            ExerciseName = "Squat",
                            Instructions = "Stand with feet shoulder-width apart, squat down by bending knees and hips, then stand back up.",
                            MuscleGroup = "Legs",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=Dy28eq2PjcM"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5418),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5419),
                            EquipmentNeeded = "Barbell",
                            ExerciseName = "Bench Press",
                            Instructions = "Lie on a bench, lower the barbell to your chest, and push it back up.",
                            MuscleGroup = "Chest",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=gRVjAtPip0Y"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5422),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5423),
                            EquipmentNeeded = "Barbell",
                            ExerciseName = "Deadlift",
                            Instructions = "Lift the barbell from the ground by extending your hips and knees while maintaining a straight back.",
                            MuscleGroup = "Back",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=1ZXobu7JvvE"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5425),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5426),
                            EquipmentNeeded = "None",
                            ExerciseName = "Push-Up",
                            Instructions = "Lower your body towards the ground by bending your elbows, then push back up.",
                            MuscleGroup = "Chest",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=_l3ySVKYVJ8"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5428),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5429),
                            EquipmentNeeded = "Pull-up Bar",
                            ExerciseName = "Pull-Up",
                            Instructions = "Hang from a bar and pull your chin above the bar, then lower down.",
                            MuscleGroup = "Back",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=eGo4IYlbE5g"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5431),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5432),
                            EquipmentNeeded = "None",
                            ExerciseName = "Lunges",
                            Instructions = "Step forward and lower your body until both knees are bent at 90 degrees, then return to standing.",
                            MuscleGroup = "Legs",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=QOVaa9B7nlA"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5434),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5435),
                            EquipmentNeeded = "Dumbbells",
                            ExerciseName = "Bicep Curl",
                            Instructions = "Hold dumbbells and curl them upwards by bending your elbows, then lower down slowly.",
                            MuscleGroup = "Arms",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=ykJmrZ5v0Oo"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5437),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5438),
                            EquipmentNeeded = "None",
                            ExerciseName = "Plank",
                            Instructions = "Hold a push-up position with your forearms on the ground, keeping your body straight.",
                            MuscleGroup = "Core",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=pSHjTRCQxIw"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5440),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5441),
                            EquipmentNeeded = "Dumbbells",
                            ExerciseName = "Shoulder Press",
                            Instructions = "Press the dumbbells upward overhead, then lower them back to shoulder height.",
                            MuscleGroup = "Shoulders",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=B-aVuyhvLHU"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5443),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5444),
                            EquipmentNeeded = "Lat Pulldown Machine",
                            ExerciseName = "Lat Pulldown",
                            Instructions = "Pull the bar down towards your chest while keeping your torso upright, then return slowly.",
                            MuscleGroup = "Back",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=AOpi-p0cJkc"
                        });
                });

            modelBuilder.Entity("The_Right_Fit.Domain.FoodItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsCustom")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServingSizeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 130,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5617),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5618),
                            IsCustom = 0,
                            Name = "White Rice",
                            ServingSizeDescription = "100g",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 165,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5621),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5622),
                            IsCustom = 0,
                            Name = "Chicken Breast",
                            ServingSizeDescription = "100g",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 105,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5625),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5626),
                            IsCustom = 0,
                            Name = "Banana",
                            ServingSizeDescription = "1 medium (118g)",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 72,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5832),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5833),
                            IsCustom = 0,
                            Name = "Egg",
                            ServingSizeDescription = "1 whole egg",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 95,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5836),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5837),
                            IsCustom = 0,
                            Name = "Apple",
                            ServingSizeDescription = "1 medium (182g)",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 70,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5839),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5840),
                            IsCustom = 0,
                            Name = "Whole Wheat Bread",
                            ServingSizeDescription = "1 slice",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 150,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5842),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5843),
                            IsCustom = 0,
                            Name = "Oatmeal",
                            ServingSizeDescription = "40g (1/2 cup dry)",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 103,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5845),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5846),
                            IsCustom = 0,
                            Name = "Milk",
                            ServingSizeDescription = "250ml",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 59,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5848),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5849),
                            IsCustom = 0,
                            Name = "Greek Yogurt",
                            ServingSizeDescription = "100g",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 208,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5851),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(5851),
                            IsCustom = 0,
                            Name = "Salmon",
                            ServingSizeDescription = "100g",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("The_Right_Fit.Domain.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerIdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutLog");
                });

            modelBuilder.Entity("The_Right_Fit.Domain.WorkoutLogExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualReps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActualSets")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutLogExercise");
                });

            modelBuilder.Entity("The_Right_Fit.Domain.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("int");

                    b.Property<string>("GoalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerIdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("PlanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6117),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6120),
                            DifficultyLevel = "Beginner",
                            DurationWeeks = 6,
                            GoalType = "General Fitness",
                            PlanName = "Beginner Full Body Program",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6122),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6123),
                            DifficultyLevel = "Beginner",
                            DurationWeeks = 4,
                            GoalType = "Weight Loss",
                            PlanName = "Fat Loss Home Workout Plan",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6126),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6126),
                            DifficultyLevel = "Intermediate",
                            DurationWeeks = 8,
                            GoalType = "Muscle Gain",
                            PlanName = "Muscle Gain Strength Program",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6129),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6129),
                            DifficultyLevel = "Intermediate",
                            DurationWeeks = 6,
                            GoalType = "Strength Training",
                            PlanName = "Upper / Lower Split",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6131),
                            DateUpdated = new DateTime(2026, 1, 18, 0, 46, 43, 885, DateTimeKind.Local).AddTicks(6132),
                            DifficultyLevel = "Advanced",
                            DurationWeeks = 8,
                            GoalType = "Muscle Gain",
                            PlanName = "Push Pull Legs (PPL) Program",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("The_Right_Fit.Domain.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlanExercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 1,
                            Reps = 10,
                            Sets = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 2,
                            Reps = 10,
                            Sets = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 8,
                            Reps = 30,
                            Sets = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 4,
                            Reps = 12,
                            Sets = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 6,
                            Reps = 10,
                            Sets = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 7,
                            Reps = 12,
                            Sets = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 2,
                            ExerciseId = 4,
                            Reps = 15,
                            Sets = 4,
                            WorkoutPlanId = 2
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 2,
                            ExerciseId = 6,
                            Reps = 12,
                            Sets = 4,
                            WorkoutPlanId = 2
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 2,
                            ExerciseId = 8,
                            Reps = 40,
                            Sets = 4,
                            WorkoutPlanId = 2
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 1,
                            Reps = 5,
                            Sets = 5,
                            WorkoutPlanId = 3
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 3,
                            Reps = 5,
                            Sets = 5,
                            WorkoutPlanId = 3
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 2,
                            Reps = 5,
                            Sets = 5,
                            WorkoutPlanId = 3
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 9,
                            Reps = 8,
                            Sets = 4,
                            WorkoutPlanId = 3
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 2,
                            Reps = 8,
                            Sets = 4,
                            WorkoutPlanId = 4
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 5,
                            Reps = 8,
                            Sets = 4,
                            WorkoutPlanId = 4
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 1,
                            Reps = 8,
                            Sets = 4,
                            WorkoutPlanId = 4
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 6,
                            Reps = 12,
                            Sets = 3,
                            WorkoutPlanId = 4
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 2,
                            Reps = 5,
                            Sets = 5,
                            WorkoutPlanId = 5
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 1,
                            ExerciseId = 9,
                            Reps = 8,
                            Sets = 4,
                            WorkoutPlanId = 5
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 5,
                            Reps = 8,
                            Sets = 4,
                            WorkoutPlanId = 5
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 3,
                            ExerciseId = 10,
                            Reps = 10,
                            Sets = 4,
                            WorkoutPlanId = 5
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 5,
                            ExerciseId = 1,
                            Reps = 5,
                            Sets = 5,
                            WorkoutPlanId = 5
                        },
                        new
                        {
                            Id = 23,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DayOfWeek = 5,
                            ExerciseId = 3,
                            Reps = 5,
                            Sets = 4,
                            WorkoutPlanId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("The_Right_Fit.Data.The_Right_FitUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("The_Right_Fit.Data.The_Right_FitUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("The_Right_Fit.Data.The_Right_FitUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("The_Right_Fit.Data.The_Right_FitUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
