// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using The_Right_Fit.Data;

#nullable disable

namespace The_Right_Fit.Migrations
{
    [DbContext(typeof(The_Right_FitContext))]
    partial class The_Right_FitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("The_Right_Fit.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SessionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("The_Right_Fit.Domain.DietLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomFoodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("QuantityServings")
                        .HasColumnType("float");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DietLog");
                });

            modelBuilder.Entity("The_Right_Fit.Domain.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("EquipmentNeeded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExerciseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(253),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(267),
                            EquipmentNeeded = "Barbell",
                            ExerciseName = "Squat",
                            Instructions = "Stand with feet shoulder-width apart, squat down by bending knees and hips, then stand back up.",
                            MuscleGroup = "Legs",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=Dy28eq2PjcM"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(273),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(274),
                            EquipmentNeeded = "Barbell",
                            ExerciseName = "Bench Press",
                            Instructions = "Lie on a bench, lower the barbell to your chest, and push it back up.",
                            MuscleGroup = "Chest",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=gRVjAtPip0Y"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(276),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(276),
                            EquipmentNeeded = "Barbell",
                            ExerciseName = "Deadlift",
                            Instructions = "Lift the barbell from the ground by extending your hips and knees while maintaining a straight back.",
                            MuscleGroup = "Back",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=1ZXobu7JvvE"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(277),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(278),
                            EquipmentNeeded = "None",
                            ExerciseName = "Push-Up",
                            Instructions = "Lower your body towards the ground by bending your elbows, then push back up.",
                            MuscleGroup = "Chest",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=_l3ySVKYVJ8"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(280),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(280),
                            EquipmentNeeded = "Pull-up Bar",
                            ExerciseName = "Pull-Up",
                            Instructions = "Hang from a bar and pull your chin above the bar, then lower down.",
                            MuscleGroup = "Back",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=eGo4IYlbE5g"
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(281),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(282),
                            EquipmentNeeded = "None",
                            ExerciseName = "Lunges",
                            Instructions = "Step forward and lower your body until both knees are bent at 90 degrees, then return to standing.",
                            MuscleGroup = "Legs",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=QOVaa9B7nlA"
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(283),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(284),
                            EquipmentNeeded = "Dumbbells",
                            ExerciseName = "Bicep Curl",
                            Instructions = "Hold dumbbells and curl them upwards by bending your elbows, then lower down slowly.",
                            MuscleGroup = "Arms",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=ykJmrZ5v0Oo"
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(285),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(286),
                            EquipmentNeeded = "None",
                            ExerciseName = "Plank",
                            Instructions = "Hold a push-up position with your forearms on the ground, keeping your body straight.",
                            MuscleGroup = "Core",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=pSHjTRCQxIw"
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(287),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(287),
                            EquipmentNeeded = "Dumbbells",
                            ExerciseName = "Shoulder Press",
                            Instructions = "Press the dumbbells upward overhead, then lower them back to shoulder height.",
                            MuscleGroup = "Shoulders",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=B-aVuyhvLHU"
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(289),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(289),
                            EquipmentNeeded = "Lat Pulldown Machine",
                            ExerciseName = "Lat Pulldown",
                            Instructions = "Pull the bar down towards your chest while keeping your torso upright, then return slowly.",
                            MuscleGroup = "Back",
                            UpdatedBy = "System",
                            VideoUrl = "https://www.youtube.com/watch?v=AOpi-p0cJkc"
                        });
                });

            modelBuilder.Entity("The_Right_Fit.Domain.FoodItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsCustom")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServingSizeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 130,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(477),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(478),
                            IsCustom = 0,
                            Name = "White Rice",
                            ServingSizeDescription = "100g",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 165,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(481),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(481),
                            IsCustom = 0,
                            Name = "Chicken Breast",
                            ServingSizeDescription = "100g",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 105,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(483),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(483),
                            IsCustom = 0,
                            Name = "Banana",
                            ServingSizeDescription = "1 medium (118g)",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 72,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(485),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(485),
                            IsCustom = 0,
                            Name = "Egg",
                            ServingSizeDescription = "1 whole egg",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 95,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(487),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(487),
                            IsCustom = 0,
                            Name = "Apple",
                            ServingSizeDescription = "1 medium (182g)",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            Calories = 70,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(489),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(489),
                            IsCustom = 0,
                            Name = "Whole Wheat Bread",
                            ServingSizeDescription = "1 slice",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 7,
                            Calories = 150,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(491),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(491),
                            IsCustom = 0,
                            Name = "Oatmeal",
                            ServingSizeDescription = "40g (1/2 cup dry)",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 8,
                            Calories = 103,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(493),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(493),
                            IsCustom = 0,
                            Name = "Milk",
                            ServingSizeDescription = "250ml",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 9,
                            Calories = 59,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(494),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(495),
                            IsCustom = 0,
                            Name = "Greek Yogurt",
                            ServingSizeDescription = "100g",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 10,
                            Calories = 208,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(496),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(497),
                            IsCustom = 0,
                            Name = "Salmon",
                            ServingSizeDescription = "100g",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("The_Right_Fit.Domain.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HeightCm")
                        .HasColumnType("float");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("The_Right_Fit.Domain.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkoutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutLog");
                });

            modelBuilder.Entity("The_Right_Fit.Domain.WorkoutLogExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualReps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActualSets")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutLogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutLogExercise");
                });

            modelBuilder.Entity("The_Right_Fit.Domain.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("int");

                    b.Property<string>("GoalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(603),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(604),
                            DifficultyLevel = "Beginner",
                            DurationWeeks = 6,
                            GoalType = "General Fitness",
                            PlanName = "Beginner Full Body Program",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(605),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(606),
                            DifficultyLevel = "Beginner",
                            DurationWeeks = 4,
                            GoalType = "Weight Loss",
                            PlanName = "Fat Loss Home Workout Plan",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(608),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(608),
                            DifficultyLevel = "Intermediate",
                            DurationWeeks = 8,
                            GoalType = "Muscle Gain",
                            PlanName = "Muscle Gain Strength Program",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(610),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(610),
                            DifficultyLevel = "Intermediate",
                            DurationWeeks = 6,
                            GoalType = "Strength Training",
                            PlanName = "Upper / Lower Split",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(612),
                            DateUpdated = new DateTime(2025, 12, 11, 21, 10, 24, 374, DateTimeKind.Local).AddTicks(612),
                            DifficultyLevel = "Advanced",
                            DurationWeeks = 8,
                            GoalType = "Muscle Gain",
                            PlanName = "Push Pull Legs (PPL) Program",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("The_Right_Fit.Domain.WorkoutPlanExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlanExercise");
                });
#pragma warning restore 612, 618
        }
    }
}
